version: '3'
services: 
    express:
        container_name: Server
        restart: "no"
        image: node:12-alpine
        command: sh -c "npm install && npm run build && npm run start"
        ports:
            - "3000:3000"
        working_dir: /usr/server
        volumes: 
           - ./server:/usr/server
        links:
            - "mysql:database"
        environment: 
            DB_HOST: database
            DB_PASSWORD: secret
    mysql:
        container_name: mysql_database
        image: mysql:5.7
        volumes: 
            - db_punto_de_venta:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: punto_de_venta
    client:
        container_name: application_client
        restart: "no"
        image: node:12-alpine
        working_dir: /usr/client
        command: sh -c "npm install && npm run build && npm install -g http-server && http-server dist/canningCart/"
        ports:
            - "8080:8080"
        volumes:
            - ./client/canningCart:/usr/client
volumes: 
    db_punto_de_venta:
